FROM oven/bun:1

WORKDIR /app

ARG DATABASE_URL

COPY ./apps/web ./apps/web
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun install
RUN apt-get update -y && apt-get install -y openssl
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 8080

CMD ["bun","run", "start:frontend"]