name: Deploying backend
on: 
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.be
          push: true
          tags: graniteviper/week-27-be:${{github.sha}}

      - name: Running service in the VM
        run: |
          echo "${{secrets.SSH_GCP_KEY}}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key tanishq@34.42.191.90 -t " sudo docker stop user_backend && sudo docker rm user_backend && sudo docker run -e DATABASE_URL=${{secrets.DATABASE_URL}} -p 8080:8080 --name "user_backend" -d graniteviper/week-27-be:${{github.sha}}"